name: askmaxie
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  google_sign_in: ^6.2.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  flutter_svg: ^2.0.17
  flutter_signin_button: ^2.0.0
  cupertino_icons: ^1.0.8
  flutter_gemini: ^2.0.5
  google_generative_ai: ^0.4.5
  flutter_dotenv: ^5.1.0
  dash_chat_2: ^0.0.15
  image_picker: ^1.1.2
  flutter_tts: ^4.0.2
  lottie: ^3.1.2
  camera: ^0.11.0+2
  speech_to_text: ^7.0.0
  dart_openai: ^5.1.0
  http: ^1.2.2 # For making HTTP requests to Google Speech-to-Text API


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
